export const handoutCatalog = [
  {
    id: 'en-classmates',
    language: 'en',
    title: '同学之间的自然交流',
    subtitle: 'Everyday connections',
    level: 'A2–B1',
    pages: 16,
    description: '从第一句搭话，到课后一起吃饭、学习。',
  },
  {
    id: 'en-academic',
    language: 'en',
    title: '学术和专业讨论英语',
    subtitle: 'Think out loud',
    level: 'B2–C1',
    pages: 12,
    description: '解释思路、澄清假设，礼貌地提出不同意见。',
  },
  {
    id: 'en-quant',
    language: 'en',
    title: 'Quant 面试英语',
    subtitle: 'Make your reasoning clear',
    level: 'B2–C1',
    pages: 14,
    description: '自我介绍、技术推导与行为面试的完整表达。',
  },
  {
    id: 'fr-daily',
    language: 'fr',
    title: '法国日常生活场景',
    subtitle: 'Le français au quotidien',
    level: 'A1–A2',
    pages: 23,
    description: '购物、点餐、交通、维修与取件，生活里的实用法语。',
  },
  {
    id: 'fr-help',
    language: 'fr',
    title: '法语礼貌与求助表达',
    subtitle: 'Un peu d’aide, s’il vous plaît',
    level: 'A1–A2',
    pages: 11,
    description: '听不懂也不慌：礼貌开口、请求重复、确认信息。',
  },
  {
    id: 'fr-classmates',
    language: 'fr',
    title: '和法国同学自然交流',
    subtitle: 'On fait connaissance ?',
    level: 'A2–B1',
    pages: 19,
    description: '认识同学、聊课程、约自习，让交流自然接下去。',
  },
] as const;
